In [122]:
from sklearn.linear_model import SGDClassifier
import numpy as np
import pandas as pd
import collections
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torch import Tensor

def cumsum(vector):
    cumulative = []
    sum =0
    for i in vector:
        if i == None:
            cumulative.append(None)
        else:
            sum += i
            cumulative.append(sum)
    return cumulative



def STAP(controler_clf, controler_input, nb_mistakes, i):    

    initial_action = controler_clf.predict(controler_input)[0]
    r = np.random.uniform(0,1)
    flip_proba = np.sqrt( (1+nb_mistakes)/(i+1) )
    if (initial_action == 1 or initial_action == 0) and r <= flip_proba:
        STAP_action = 1
    else:
        STAP_action = 0
    
    return initial_action, STAP_action

def CesaBianchi(controler_clf, controler_input, beta, K):

    controler_pred = controler_clf.decision_function(controler_input)[0]
    initial_action = controler_clf.predict(controler_input)[0] 
    p = beta / ( beta + abs( controler_pred ) )
    cesa_action = np.random.binomial(1, p)
    
    
    return initial_action, cesa_action
    

def PLOT(epsilon,):
    q = np.random.binomial(1, epsilon)


def generate_sequence(target, k, t, test_loader,n_classes,epsilon):

        R = {}
        Sa = []
        for i,data in enumerate(test_loader):
            x,y = data
            x_attacked = fgsm_attack(target, epsilon, x, y, n_classes)

            if i < t:
                v =  nn.CrossEntropyLoss()( target(x_attacked) ,y)
                R[i] = v
                R = {k: v for k, v in sorted(R.items(), key=lambda item: item[1])}
            else:
                v =  nn.CrossEntropyLoss()( target(x_attacked) ,y)
                last_value = list(R.values())[-1]
                last_key = list(R.keys())[-1]
                if v>=last_value and len(Sa)<=k:
                    del R[ last_key ]
                    R[i] = v
                    R = {k: v for k, v in sorted(R.items(), key=lambda item: item[1])}
                    Sa.append(i)

        attack_label = [ 1 if i in Sa else 0 for i in range(len(test_loader)) ]
                    
        return attack_label

def epoch(loader, model, opt=None):
    """Standard training/evaluation epoch over the dataset"""
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") 
    total_loss, total_err = 0.,0.
    for X,y in loader:
        X,y = X.to(device), y.to(device)
        yp = model(X)
        loss = nn.CrossEntropyLoss()(yp,y)
        if opt:
            opt.zero_grad()
            loss.backward()
            opt.step()
        
        total_err += (yp.max(dim=1)[1] != y).sum().item()
        total_loss += loss.item() * X.shape[0]
    return total_err / len(loader.dataset), total_loss / len(loader.dataset)


def fgsm_attack(target, epsilon, x, y, n_classes):
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") 
    
    if n_classes <=2:
        dlt =  target(x)[0] - y
    else:
        label = torch.zeros(n_classes)
        label[y] = 1
        dlt =  target.predict_proba( x ) - label

    direction = torch.sign( torch.matmul( dlt, target[0].weight ) ).to(device)
    x_attacked = x + epsilon * direction
    print(x_attacked)
    return x_attacked



In [123]:


class Task:

    def __init__(self, n, n_features, n_classes, class_sep, percent_flip, attack_proba, epsilon, seed = 42):
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") 

        X, y = make_classification(n_samples = n, n_features = n_features,  n_informative = 2, n_redundant = 1, n_classes = n_classes, flip_y = percent_flip, class_sep = class_sep, n_clusters_per_class = 1 )
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=seed)
          
        train_loader = DataLoader( TensorDataset( Tensor(X_train).to(device), Tensor(y_train).type(torch.LongTensor).to(device) ) , batch_size = 32, shuffle=True)
        test_loader = DataLoader(  TensorDataset( Tensor(X_test).to(device), Tensor(y_test).type(torch.LongTensor).to(device) ), batch_size = 1, shuffle=False)

        ### Train the target classifier:

        self.target = nn.Sequential( nn.Linear(n_features, n_classes)).to(device)
        opt = optim.SGD( self.target.parameters(), lr=1e-1 )

        for t in range(10):
            train_err, train_loss = epoch(train_loader, self.target, opt)

        self.X_train, self.y_train = X_train, y_train

        attack_label = generate_sequence(self.target, 10, 10, test_loader, n_classes, epsilon)
        #attack_label = [  np.random.choice([1,0], p=[attack_proba, 1-attack_proba]) for _ in range(len(X_test)) ]
        X_test = [ fgsm_attack(self.target, epsilon, data[0], data[1], n_classes) if attack_label[i] else data[0] for i,data in enumerate(test_loader) ]

        self.test_loader = DataLoader(  TensorDataset( torch.stack( X_test ).to(device), Tensor(y_test).type(torch.LongTensor).to(device) ), batch_size = 1, shuffle=False)
        self.attack_label = attack_label
    
    def init_controler(self,n_classes):
        controler_clf = SGDClassifier(loss = 'hinge')
        y_class = np.zeros(n_classes)
        y_class[self.y_train[0]]=1
        x_init = np.stack([self.X_train[0], y_class])
        controler_clf.partial_fit( [x_init], [0], [1,0]  ) 
        return controler_clf

    def online(self, method, beta=1 ):

        controler_clf = self.init_controler()
        regrets = []
        K, attacks,i, abs_false_pos, abs_true_pos, false_pos, true_pos,  = 0,0,0,0,0,0,0
        for i,data in enumerate(self.test_loader):
            x, y_true = data 
            is_attacked = self.attack_label

            target_pred = self.target([x]) 

            controler_input = np.reshape( np.concatenate(( x, target_pred[0])), (1,-1) )

            if method == 'STAP':
                initial_action, decision = STAP(controler_clf, controler_input, K, i) 
            elif method == 'Cesa':
                initial_action, decision = CesaBianchi(controler_clf, controler_input, beta, K)

            if decision == 1:
                if is_attacked != initial_action:
                    controler_clf.partial_fit(controler_input, [is_attacked], [1,0])  
                    K = K+1  

            abs_true_pos = abs_true_pos+1 if decision == 1 and is_attacked == 1 else abs_true_pos
            abs_false_pos = abs_false_pos+1 if decision == 1 and is_attacked == 0 else abs_false_pos
            true_pos = true_pos+1 if initial_action == 1 and is_attacked == 1 else true_pos
            false_pos = false_pos+1 if initial_action == 1 and is_attacked == 0 else false_pos
            regret = abs( decision - is_attacked)
            regrets.append(regret)
            attacks = attacks+1 if is_attacked == 1 else attacks
            i+=1

        plt.plot( cumsum(regrets) )
        plt.xlabel('Iteration')
        plt.ylabel('Cumulative Regret')
        print('     True positive:{},      False positive:{}'.format(true_pos,false_pos,attacks))
        print('Abs. True positive:{}, Abs. False positive:{}, Attacks:{}'.format(abs_true_pos,abs_false_pos,attacks))
                
    def offline(self):

        attack_clf = SGDClassifier(loss = 'hinge')
        train_attack_label = [  np.random.choice([1,0], p=[attack_proba, 1-attack_proba]) for _ in range(len(self.X_train)) ]
        X_train_attacks = [ fgsm_attack(self.target, epsilon, [x], y, n_classes) if is_attacked else x for x,y, is_attacked in zip(self.X_train, self.y_train, train_attack_label)  ]
        X_train_attacks = np.concatenate( X_train_attacks, axis=0 )
    
        attack_clf.fit( X_train_attacks, train_attack_label ) 
        y_pred = attack_clf.predict( self.X_test )

        tn, fp, fn, tp = confusion_matrix( self.attack_label , y_pred).ravel()
        print('True positive:{}, False positive:{}, Attacks:{}'.format(tp,fp,sum(self.attack_label) ) )
        
    

In [124]:
n = 1000
n_classes = 2
classes =  np.arange(0, n_classes)
attack_proba =  0.1
epsilon = 1
n_features = 10
class_sep = 1
percent_flip = 0.1

task = Task(n, n_features, n_classes, class_sep, percent_flip, attack_proba, epsilon)

# print("Online STAP:")
# task.online('STAP')
# print()
# print("Online Cesa Bianchi:")
# task.online('Cesa',5)
# print()
# print("Offline:")
# task.offline()

tensor([[ 2.3975,  1.5812, -0.1992,  1.1206, -0.8399, -0.3393,  2.3660, -1.0942,
         -2.3055,  0.6350]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[-0.9575, -1.1749, -0.5421,  1.0577,  0.4617,  0.2344,  1.4162, -0.9668,
         -2.8267,  0.5429]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[ 0.0948,  1.2115, -1.2424, -0.7527,  2.8178, -2.1191, -1.6251,  1.4717,
          2.7110, -1.2371]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[-1.2654,  1.5502, -3.7831,  0.3345,  1.4591, -0.3052, -0.0434,  1.3577,
          0.2231, -2.0333]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[ 1.6473,  2.5423,  0.1355,  0.6326, -1.3678,  2.7336, -0.0667,  0.6064,
         -1.7647,  0.7223]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[-0.4027,  0.1670, -1.4825,  2.2165,  1.8728, -1.9534, -1.8340, -0.3754,
          3.6605, -1.4103]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[ 0.9446, -2.0380,  0.0688, -1.1775, -1.1842,  1.8475,  2.2990,  0.2875,
         -1.8