# Label Efficient game:

In [2]:
import geometry_v5
import games
import numpy as np
import geometry
outcome_distribution =  {'spam':0.05,'ham':0.95}
game = games.label_efficient()
FeedbackMatrix = np.array(  [ [1, 1/2], [1/4, 1/4], [1/4, 1/4] ] )
LossMatrix =  np.array( [ [1, 1],[1, 0],[0, 1] ] )

print('global observability:', geometry.GlobalObservableGame(game) )
print()
print('local observability', geometry.LocalObservableGame(game) )
print()

p = np.array([0.05,0.95])

for i in range(3):
    print('action',i,'expected loss', LossMatrix[i,...].T @ p, 'pareto?', geometry_v5.isParetoOptimal(i, LossMatrix),  )
print()
for pair in  [ [1,2], [2,1]  ]:
    a,b = pair
    print('pair', pair, 'neighbors?', geometry_v5.areNeighbours(a, b, LossMatrix), ' -> neighbohood', geometry_v5.neighborhood(a,b, LossMatrix), 'observable?',
     geometry.ObservablePair(a, b, LossMatrix, [geometry.signal_vecs(i, game.FeedbackMatrix) for i in geometry.Neighbourhood(a, b, LossMatrix)]),
     'delta', (LossMatrix[a,...] - LossMatrix[b,...]).T @ p )

import geometry_v3

geometry_v3.getV(LossMatrix, game.N, game.M, FeedbackMatrix, game.SignalMatrices, game.mathcal_N, game.V)

global observability: (True, 'all pairs are globally observable.')

local observability (False, '[2,1] pair is not locally observable.')

action 0 expected loss 1.0 pareto? False
action 1 expected loss 0.05 pareto? True
action 2 expected loss 0.95 pareto? True

pair [1, 2] neighbors? True  -> neighbohood [1, 2] observable? False delta -0.8999999999999999
pair [2, 1] neighbors? True  -> neighbohood [1, 2] observable? False delta 0.8999999999999999
vars defaultdict(<class 'dict'>, {0: [<gurobi.Var v_1_2_0>, <gurobi.Var v_1_2_1>], 1: [<gurobi.Var v_1_2_0>], 2: [<gurobi.Var v_1_2_0>]})
signal (2, 2) vars [<gurobi.Var v_1_2_0>, <gurobi.Var v_1_2_1>]
signal (1, 2) vars [<gurobi.Var v_1_2_0>]
signal (1, 2) vars [<gurobi.Var v_1_2_0>]
vars defaultdict(<class 'dict'>, {0: [<gurobi.Var v_2_1_0>, <gurobi.Var v_2_1_1>], 1: [<gurobi.Var v_2_1_0>], 2: [<gurobi.Var v_2_1_0>]})
signal (2, 2) vars [<gurobi.Var v_2_1_0>, <gurobi.Var v_2_1_1>]
signal (1, 2) vars [<gurobi.Var v_2_1_0>]
signal (1, 2) vars 

defaultdict(dict,
            {1: {2: {0: array([-1.,  1.]),
               1: array([-2.22044223e-17]),
               2: array([-2.22044223e-17])}},
             2: {1: {0: array([ 1., -1.]),
               1: array([2.22044223e-17]),
               2: array([2.22044223e-17])}}})

In [20]:
diff

array([ 1, -1])

In [26]:
i,j = 0,1
print( game.SignalMatrices[i].shape) 
print( game.SignalMatrices[i]) 
print()
print( game.SignalMatrices[j].shape)
print( game.SignalMatrices[j]) 
vec = np.hstack([game.SignalMatrices[i].T ,  game.SignalMatrices[j].T  ])
print( vec.shape )
diff = LossMatrix[i] - LossMatrix[j]

pinv = np.linalg.pinv(vec)
res = pinv @  diff
res

(2, 2)
[[0 1]
 [1 0]]

(1, 2)
[[1 1]]
(2, 3)


array([ 0.66666667, -0.33333333,  0.33333333])

# Apple Tasting game:

In [1]:
import geometry_v5
import games
import numpy as np
import geometry
import geometry_v3
outcome_distribution =  {'spam':0.05,'ham':0.95}
game = games.apple_tasting(False)
LossMatrix = np.array( [ [1, 0], [0, 1] ] )
FeedbackMatrix =  np.array([ [1, 1],[1, 0] ])

print('global observability:', geometry.GlobalObservableGame(game) )
print()
print('local observability', geometry.LocalObservableGame(game) )
print()

p = np.array([0.05,0.95])

for i in range(2):
    print('action',i,'expected loss', LossMatrix[i,...].T @ p, 'pareto?', geometry_v5.isParetoOptimal(i, LossMatrix),  )
print()
for pair in  [ [0,1], [1,0]  ]:
    a,b = pair
    print('pair', pair, 'neighbors?', geometry_v5.areNeighbours(a, b, LossMatrix), ' -> neighbohood', geometry_v5.neighborhood(a,b, LossMatrix), 'observable?',
     geometry.ObservablePair(a, b, LossMatrix, [geometry.signal_vecs(i, game.FeedbackMatrix) for i in geometry.Neighbourhood(a, b, LossMatrix)]),
     'delta', (LossMatrix[a,...] - LossMatrix[b,...]).T @ p )

geometry_v3.getV(LossMatrix, game.N, game.M, FeedbackMatrix, game.SignalMatrices, game.mathcal_N, game.V)

global observability: (True, 'all pairs are globally observable.')

local observability (True, 'all neighbouring pairs are observable.')

action 0 expected loss 0.05 pareto? True
action 1 expected loss 0.95 pareto? True

pair [0, 1] neighbors? True  -> neighbohood [0, 1] observable? True delta -0.8999999999999999
pair [1, 0] neighbors? True  -> neighbohood [0, 1] observable? True delta 0.8999999999999999
Restricted license - for non-production use only - expires 2023-10-25
vars defaultdict(<class 'dict'>, {0: [<gurobi.Var v_0_1_0>], 1: [<gurobi.Var v_0_1_0>, <gurobi.Var v_0_1_1>]})
signal (1, 2) vars [<gurobi.Var v_0_1_0>]
signal (2, 2) vars [<gurobi.Var v_0_1_0>, <gurobi.Var v_0_1_1>]
vars defaultdict(<class 'dict'>, {0: [<gurobi.Var v_1_0_0>], 1: [<gurobi.Var v_1_0_0>, <gurobi.Var v_1_0_1>]})
signal (1, 2) vars [<gurobi.Var v_1_0_0>]
signal (2, 2) vars [<gurobi.Var v_1_0_0>, <gurobi.Var v_1_0_1>]


defaultdict(dict,
            {0: {1: {0: array([0.]), 1: array([-1.,  1.])}},
             1: {0: {0: array([0.]), 1: array([ 1., -1.])}}})

# Dynamic Pricing

In [1]:
import geometry_v5
import geometry
import numpy as np

c = 2
LossMatrix = np.array( [ [0,1,2,3,4], [c,0,1,2,3],[c,c,0,1,2],[c,c,c,0,1],[c,c,c,c,0] ] )
FeedbackMatrix = np.array( [ [2,2,2,2,2], [1,2,2,2,2],[1,1,2,2,2],[1,1,1,2,2],[1,1,1,1,2] ] )

SignalMatrices = [  np.array( [ [0,0,0,0,0],[1,1,1,1,1] ] ), 
                    np.array( [ [1,0,0,0,0],[0,1,1,1,1] ] ), 
                    np.array( [ [1,1,0,0,0],[0,0,1,1,1] ] ),
                    np.array( [ [1,1,1,0,0],[0,0,0,1,1] ] ),
                    np.array( [ [1,1,1,1,0],[0,0,0,0,1] ] ) ] 

p = np.array([0.2,0.2,0.2,0.2,0.2])

for i in range(len(LossMatrix)):
    print('action',i,'expected loss', LossMatrix[i,...].T @ p, 'pareto?', geometry_v5.isParetoOptimal(i, LossMatrix),  )
print()

from itertools import combinations, permutations
liste = list(permutations([0,1,2,3,4], 2))

for pair in liste:
    print(pair)
    a,b = pair
    print('pair', pair, 'neighbors?', geometry_v5.areNeighbours(a, b, LossMatrix), ' -> neighbohood', geometry_v5.neighborhood(a,b, LossMatrix), 'observable?',
     geometry.ObservablePair(a, b, LossMatrix, [geometry.signal_vecs(i, FeedbackMatrix) for i in geometry.Neighbourhood(a, b, LossMatrix)]),
     'delta', (LossMatrix[a,...] - LossMatrix[b,...]).T @ p )


action 0 expected loss 2.0000000000000004 pareto? True
action 1 expected loss 1.6000000000000003 pareto? True
action 2 expected loss 1.4000000000000004 pareto? True
action 3 expected loss 1.4000000000000004 pareto? True
action 4 expected loss 1.6 pareto? True

(0, 1)
pair (0, 1) neighbors? True  -> neighbohood [0, 1] observable? True delta 0.4
(0, 2)
pair (0, 2) neighbors? True  -> neighbohood [0, 2] observable? False delta 0.6000000000000001
(0, 3)
pair (0, 3) neighbors? True  -> neighbohood [0, 3] observable? False delta 0.6000000000000001
(0, 4)
pair (0, 4) neighbors? True  -> neighbohood [0, 4] observable? False delta 0.4
(1, 0)
pair (1, 0) neighbors? True  -> neighbohood [0, 1] observable? True delta -0.4
(1, 2)
pair (1, 2) neighbors? True  -> neighbohood [1, 2] observable? True delta 0.2
(1, 3)
pair (1, 3) neighbors? True  -> neighbohood [1, 3] observable? False delta 0.2
(1, 4)
pair (1, 4) neighbors? True  -> neighbohood [1, 4] observable? False delta 5.551115123125783e-17
(2, 0

In [38]:

### check the set of feasible actions given generation of random probabilities:

a = 0.51
LossMatrix = np.array([ [a, a],[1,0],[0,1] ])

possible_actions = set()
i = 0 
while i < 10000:

    p = np.random.uniform(0,1,2)
    p = p / p.sum()
    min = np.argmin(LossMatrix @ p)
    possible_actions.add(min)
    i +=1

print(possible_actions)

{1, 2}


In [37]:
import numpy as np 
c = 2
LossMatrix = np.array( [ [0,1,2,3,4], [c,0,1,2,3],[c,c,0,1,2],[c,c,c,0,1],[c,c,c,c,0] ] )
a = 4

i = 0 
possible = 0
while i < 1000:

    cell = LossMatrix[a,...] - LossMatrix
    p = np.random.uniform(0,1,5)
    p = p / p.sum()

    res = cell @ p
    if (res <= 0).all():
        possible += 1
    i +=1

print(possible)

152


In [42]:
import geometry_v5
for pair in [ [0,1], [0,2], [0,3], [0,4], [1] ]:
    areNeighbours

False